// Generated by CoffeeScript 1.3.3
(function() {
  var ZuulClient, request;

  request = require("request");

  ZuulClient = (function() {

    function ZuulClient() {}

    ZuulClient.prototype.login = function(username, password, callback) {
      return request({
        uri: "http://mparrish_15mbp.zuul1.f4tech.com:3000/key.js",
        method: "PUT",
        body: JSON.stringify({
          username: username,
          password: password
        })
      }, function(error, response, body) {
        var authenticateResult;
        console.log(response.statusCode, body);
        authenticateResult = response.statusCode === 200 && JSON.parse(body);
        return typeof callback === "function" ? callback(authenticateResult) : void 0;
      });
    };

    return ZuulClient;

  })();

  exports.Client = ZuulClient;

}).call(this);
