// Generated by CoffeeScript 1.3.3
(function() {
  var zuulclient;

  zuulclient = require('../zuulclient/client');

  exports.login = function(req, res) {
    var password, username;
    username = req.params.username;
    password = req.params.password;
    console.log("Trying to authenticate " + username);
    zuulclient = new zuulclient.Client();
    return zuulclient.loggin(username, password, function(authenticateResult) {
      if (authenticateResult.authKey != null) {
        res.cookie('ZSESSIONID', authenticateResult.authKey._ref, {
          maxAge: 900000,
          httpOnly: false
        });
        return res.end('SUCCESS');
      } else {
        return res.end('FAILURE');
      }
    });
  };

}).call(this);
