// Generated by CoffeeScript 1.3.3
(function() {
  var app, auth, express, http, path;

  express = require('express');

  path = require('path');

  http = require('http');

  auth = require('./routes/login');

  app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    return app.use(express["static"](path.join(__dirname, '../../public')));
  });

  app.post('/login', auth.login);

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + (app.get('port')));
  });

}).call(this);
